<?php

# OPERADORES DE ATRUBUIÇÃO COMBINADO
# PERMITEM ALTERAR O VALOR DE UMA VARIAVEL, PARTIR DO SEU VALOR ORIGINAL

$a = 10;

$a = $a + 20; # 30
$a = $a - 3; # 7
$a = $a * 2; # 20
$a = $a / 2; # 5

# Simplificado
$a += 20; # 30
$a -= 3;  # 7
$a *= 2;  # 20
$a /= 2;  # 5 

# OPERADORES DE INCREMENTO E DECREMENTO
# ADICIONAM OU SUBSTRAIREM UMA UNDADE A VARIAVEL

$a = 1;

$a++; # $a = $a + 1;
$a++; # $a = $a - 1;

# OPARADORES DE INCREMENTO E DECREMENTO
# ADICIONAM OU SUBSTRAEM UMA UNIDADE A VARIAVEL

# OS OPERADORES PODEM SER DE PRE-INCREMENTO OU POS-INCREMENTO
# MESMO ACONTECE PARA O DECREMENTO 

$a = 100;

$a++; # PRIMIERO ELE EXECUTA A OPERAÇÃO, DEPOIS FAZ A ADIÇÃO
++$a; # PRIMEIRO ELE FAZ A ADICIÇÃO, DEPOIS A OPERAÇÃO 

$a--; # PRIMEIRO ELE EXECUTA A OPERAÇÃO, DEPOIS FAZ A SUBSTRAÇÃO
--$a; # PRIMEIRO ELE FAZ A SUBSTRAÇÃO, DEPOIS A OPERAÇÃO 